### ISSUE TITLE
Error with Github API 

### ISSUE THREAD

**Issue by ofilangi** [p2m2/service-rdf-database-deployment#60]
## YAML / Gitlab CI For NCBI Taxon

```
include:
  - remote: 'https://raw.githubusercontent.com/p2m2/service-rdf-database-deployment/latest/msd-deploy.yml'

fetch_info_database:
  stage: version
  tags: [bash]
  only:
    - tags
    - main
  variables:
    D: https://api.github.com/repos/obophenotype/ncbitaxon/releases/latest
  script:
    - echo " ========================================================"
    - echo " =============== Manage NCBI Taxon ====="
    - echo " ========================================================"
    - echo "CATEGORY=taxon" >> build.env
    - echo "DATABASE=ncbi" >> build.env
    - RES=$(curl -s $D | jq -r '.assets[] | select(.name|test("ncbitaxon.owl$"))')
    - FILE=$(echo $RES | jq -r '.browser_download_url')
    - echo "RDF_INPUT_FILES=$FILE" >> build.env
    - VERSION=$(echo $RES | jq -r '.updated_at' | egrep -o '[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}' | uniq | tail -n1)
    - echo "VERSION=$VERSION" >> build.env
  artifacts:
    reports:
      dotenv: build.env

```

### Test of out.sh in command line
```bash
wget --spider -nv -r -nd --no-parent -e robots=off -A "$(basename https://github.com/obophenotype/ncbitaxon/releases/download/v2023-02-24/ncbitaxon.owl)" $(dirname https://github.com/obophenotype/ncbitaxon/releases/download/v2023-02-24/ncbitaxon.owl)/ 2>&1
https://github.com/obophenotype/ncbitaxon/releases/download/v2023-02-24/:
Remote file does not exist -- broken link!!!
Found 1 broken link.

https://github.com/obophenotype/ncbitaxon/releases/download/v2023-02-24/
```
